% This file was automatically generated by the LLM system
%%%%%%%%%%%%%%%%%%%%%%%
% kb
%%%%%%%%%%%%%%%%%%%%%%%
% Positions
pos(1,1).
pos(2,2).
pos(3,3).
pos(6,6).
pos(7,6).

% Blocks
block(b1).
block(b2).
block(b3).

% Agents
agent(a1).

% Resources
resources(agent(_)).

%%%%%%%%%%%%%%%%%%%%%%%
% init
%%%%%%%%%%%%%%%%%%%%%%%
init_state([
  ontable(b1), ontable(b2), ontable(b3),
  at(b1,1,1), at(b2,2,2), at(b3,3,3),
  clear(b1), clear(b2), clear(b3),
  available(a1)
]).

%%%%%%%%%%%%%%%%%%%%%%%
% goal
%%%%%%%%%%%%%%%%%%%%%%%
goal_state([
  ontable(b1), ontable(b2), ontable(b3),
  on(b3, b1), on(b3, b2),
  at(b1,6,6), at(b2,7,6), at(b3,6,6),
  clear(b1), clear(b2),
  available(a1)
]).

%%%%%%%%%%%%%%%%%%%%%%%
% actions
%%%%%%%%%%%%%%%%%%%%%%%
% Move a block from a position on the table to another position on the table
action(move_table_to_table_start(Agent, Block, X1, Y1, X2, Y2),
  [ontable(Block), at(Block, X1, Y1), available(Agent), clear(Block)],
  [at(_, X2, Y2), on(Block, _), moving_table_to_table(_, Block, _, _, _, _), moving_table_to_block(_, Block, _, _, _, _, _)],
  [],
  [agent(Agent), pos(X1, Y1), pos(X2, Y2), block(Block)],
  [
    del(available(Agent)), del(clear(Block)), del(ontable(Block)), del(at(Block, X1, Y1)),
    add(moving_table_to_table(Agent, Block, X1, Y1, X2, Y2))
  ]
).
action(move_table_to_table_end(Agent, Block, X1, Y1, X2, Y2),
  [moving_table_to_table(Agent, Block, X1, Y1, X2, Y2)],
  [at(X2, Y2)],
  [],
  [agent(Agent)],
  [
    del(moving_table_to_table(Agent, Block, X1, Y1, X2, Y2)),
    add(ontable(Block)), add(at(Block, X2, Y2)), add(clear(Block)), add(available(Agent))
  ]
).

% Move a block from a position on the table to the top of another block
action(move_table_to_block_start(Agent, Block1, Block2, X1, Y1, X2, Y2),
  [ontable(Block1), at(Block1, X1, Y1), at(Block2, X2, Y2), clear(Block2), available(Agent)],
  [on(_, Block1), on(Block1, _), moving_table_to_table(_, Block, _, _, _, _), moving_table_to_block(_, Block, _, _, _, _, _)],
  [],
  [agent(Agent), pos(X1, Y1), pos(X2, Y2), block(Block1), block(Block2), Block1 \= Block2],
  [
    del(available(Agent)), del(clear(Block1)), del(ontable(Block1)), del(at(Block1, X1, Y1)),
    add(moving_table_to_block(Agent, Block1, Block2, X1, Y1, X2, Y2))
  ]
).
action(move_table_to_block_end(Agent, Block1, Block2, X1, Y1, X2, Y2),
  [moving_table_to_block(Agent, Block1, Block2, X1, Y1, X2, Y2), clear(Block2)],
  [],
  [],
  [agent(Agent)],
  [
    del(clear(Block2)), del(moving_table_to_block(Agent, Block1, Block2, X1, Y1, X2, Y2)),
    add(on(Block1, Block2)), add(at(Block1, X2, Y2)), add(clear(Block1)), add(available(Agent))
  ]
).

% Move a block from the top of another block to a position on the table
action(move_block_to_table_start(Agent, Block, X1, Y1, X2, Y2),
  [on(Block, Block2), at(Block, X1, Y1), at(Block2, X1, Y1), clear(Block), available(Agent)],
  [ontable(Block), moving_block_to_table(_, Block, _, _, _, _), moving_block_to_block(_, Block, _, _, _, _, _)],
  [],
  [agent(Agent), pos(X1, Y1), pos(X2, Y2), block(Block), block(Block2)],
  [
    del(available(Agent)), del(clear(Block)), del(on(Block, Block2)), del(at(Block, X1, Y1)),
    add(moving_block_to_table(Agent, Block, X1, Y1, X2, Y2))
  ]
).
action(move_block_to_table_end(Agent, Block, X1, Y1, X2, Y2),
  [moving_block_to_table(Agent, Block, X1, Y1, X2, Y2)],
  [at(X2, Y2)],
  [],
  [agent(Agent)],
  [
    del(moving_block_to_table(Agent, Block, X1, Y1, X2, Y2)),
    add(ontable(Block)), add(at(Block, X2, Y2)), add(clear(Block)), add(available(Agent))
  ]
).

% Move a block from the top of another block to the top of another block
action(move_block_to_block_start(Agent, Block1, Block2, X1, Y1, X2, Y2),
  [on(Block1, Block3), at(Block1, X1, Y1), at(Block2, X2, Y2), clear(Block2), available(Agent)],
  [ontable(Block1), on(_, Block1), on(Block1, _), moving_block_to_table(_, Block, _, _, _, _), moving_block_to_block(_, Block, _, _, _, _, _)],
  [],
  [agent(Agent), pos(X1, Y1), pos(X2, Y2), block(Block1), block(Block2), block(Block3), Block1 \= Block2, Block1 \= Block3, Block2 \= Block3],
  [
    del(available(Agent)), del(clear(Block1)), del(on(Block1, Block3)), del(at(Block1, X1, Y1)),
    add(moving_block_to_block(Agent, Block1, Block2, X1, Y1, X2, Y2))
  ]
).
action(move_block_to_block_end(Agent, Block1, Block2, X1, Y1, X2, Y2),
  [moving_block_to_block(Agent, Block1, Block2, X1, Y1, X2, Y2), clear(Block2)],
  [],
  [],
  [agent(Agent)],
  [
    del(clear(Block2)), del(moving_block_to_block(Agent, Block1, Block2, X1, Y1, X2, Y2)),
    add(on(Block1, Block2)), add(at(Block1, X2, Y2)), add(clear(Block1)), add(available(Agent))
  ]
).

% Place the last block on top as an architrave
action(place_architrave_start(Agent, Block1, Block2, Block3, X1, Y1, X2, Y2, X3, Y3),
  [on(Block1, Block2), on(Block3, Block2), at(Block1, X1, Y1), at(Block2, X2, Y2), at(Block3, X3, Y3), clear(Block3), available(Agent)],
  [ontable(Block1), on(_, Block1), on(Block1, _), moving_block_to_table(_, Block, _, _, _, _), moving_block_to_block(_, Block, _, _, _, _, _)],
  [],
  [agent(Agent), pos(X1, Y1), pos(X2, Y2), pos(X3, Y3), block(Block1), block(Block2), block(Block3), Block1 \= Block2, Block1 \= Block3, Block2 \= Block3],
  [
    del(available(Agent)), del(clear(Block1)), del(on(Block1, Block2)), del(on(Block3, Block2)), del(at(Block1, X1, Y1)),
    add(moving_block_to_block(Agent, Block1, Block3, X1, Y1, X3, Y3))
  ]
).
action(place_architrave_end(Agent, Block1, Block2, Block3, X1, Y1, X2, Y2, X3, Y3),
  [moving_block_to_block(Agent, Block1, Block3, X1, Y1, X3, Y3), clear(Block3)],
  [],
  [],
  [agent(Agent)],
  [
    del(clear(Block3)), del(moving_block_to_block(Agent, Block1, Block3, X1, Y1, X3, Y3)),
    add(on(Block1, Block3)), add(at(Block1, X3, Y3)), add(clear(Block1)), add(available(Agent))
  ]
).
