# Backend Dockerfile
FROM ubuntu:22.04

RUN apt-get update
RUN apt-get -y install software-properties-common
RUN apt-add-repository ppa:swi-prolog/stable
RUN apt-get update
RUN apt-get -y install swi-prolog python3 python3-pip iputils-ping
RUN apt-get -y install python3-dev graphviz libgraphviz-dev pkg-config


# Set the working directory
WORKDIR /app

# Copy the requirements file
COPY ./requirements.txt ./requirements.txt
COPY ./llm_kb_gen/requirements.txt ./llm_kb_gen/requirements.txt
COPY ./llm_ll_gen/requirements.txt ./llm_ll_gen/requirements.txt
COPY ./LLM/requirements.txt ./LLM/requirements.txt
COPY ./python_interface/requirements.txt ./python_interface/requirements.txt
COPY ./llm_ui/backend/requirements.txt ./llm_ui/backend/requirements.txt

# Install Python dependencies
RUN python3 -m pip install --no-cache-dir -r ./requirements.txt

# Expose the backend port
EXPOSE 5000

# Change the working directory
WORKDIR /app/llm_ui/backend/

# Start the Flask server
CMD ["python3", "run.py", "-d"]
