% This file was automatically generated by the LLM system
%%%%%%%%%%%%%%%%%%%%%%%
% kb
%%%%%%%%%%%%%%%%%%%%%%%
% Positions
pos(1,1).
pos(2,2).
pos(3,3).
pos(10,10).

% Blocks
block(b1).
block(b2).
block(b3).
block(b4).
block(b5).
block(b6).

% Agents
agent(a1).
agent(a2).

% Arms
ll_arm(a1).
ll_arm(a2).

% Resources
resources(agent(_)).
resources(ll_arm(_)).

%%%%%%%%%%%%%%%%%%%%%%%
% init
%%%%%%%%%%%%%%%%%%%%%%%
init_state([
  ll_ontable(b1), ll_ontable(b2), ll_ontable(b3), ll_on(b4, b1), ll_on(b5, b2), ll_on(b6, b3),
  ll_at(b1,1,1), ll_at(b2,2,2), ll_at(b3,3,3), ll_at(b4,1,1), ll_at(b5,2,2), ll_at(b6,3,3),
  ll_clear(b4), ll_clear(b5), ll_clear(b6),
  ll_available(a1), ll_available(a2),
  ll_arm_at(a1,4,4), ll_arm_at(a2,5,5),
  ll_gripper(a1,open), ll_gripper(a2,open)
]).

%%%%%%%%%%%%%%%%%%%%%%%
% goal
%%%%%%%%%%%%%%%%%%%%%%%
goal_state([
  ll_ontable(b1), ll_ontable(b2), ll_ontable(b3), ll_on(b5, b4),
  ll_at(b1,1,1), ll_at(b2,2,2), ll_at(b3,3,3), ll_at(b4,10,10), ll_at(b5,10,10), ll_at(b6,3,3),
  ll_clear(b1), ll_clear(b2), ll_clear(b3), ll_clear(b6),
  ll_available(a1), ll_available(a2),
  ll_arm_at(a1,_,_), ll_arm_at(a2,_,_),
  ll_gripper(a1,_), ll_gripper(a2,_)
]).

%%%%%%%%%%%%%%%%%%%%%%%
% actions
%%%%%%%%%%%%%%%%%%%%%%%
% Move a block from a position on the table to another position on the table
action(move_table_to_table_start(Agent, Block, X1, Y1, X2, Y2),
  [available(Agent), ontable(Block), at(Block, X1, Y1), clear(Block)],
  [at(_, X2, Y2), on(_, Block), moving_table_to_table(_, Block, _, _, _, _), moving_table_to_block(_, Block, _, _, _, _, _)],
  [],
  [agent(Agent), pos(X1, Y1), pos(X2, Y2), block(Block)],
  [
    del(available(Agent)), del(clear(Block)), del(ontable(Block)), del(at(Block, X1, Y1)),
    add(moving_table_to_table(Agent, Block, X1, Y1, X2, Y2))
  ]
).
action(move_table_to_table_end(Agent, Block, X1, Y1, X2, Y2),
  [moving_table_to_table(Agent, Block, X1, Y1, X2, Y2)],
  [at(X2, Y2)],
  [],
  [agent(Agent)],
  [
    del(moving_table_to_table(Agent, Block, X1, Y1, X2, Y2)),
    add(at(Block, X2, Y2)), add(available(Agent))
  ]
).
% Move a block from a position on the table to the top of another block
action(move_table_to_block_start(Agent, Block1, Block2, X1, Y1, X2, Y2),
  [available(Agent), ontable(Block1), at(Block1, X1, Y1), at(Block2, X2, Y2), clear(Block2), clear(Block1)],
  [on(_, Block1), on(Block1, _), moving_table_to_table(_, Block, _, _, _, _), moving_table_to_block(_, Block, _, _, _, _, _)],
  [],
  [agent(Agent), pos(X1, Y1), pos(X2, Y2), block(Block1), block(Block2), Block1 \= Block2],
  [
    del(available(Agent)), del(clear(Block1)), del(ontable(Block1)), del(at(Block1, X1, Y1)),
    add(moving_table_to_block(Agent, Block1, Block2, X1, Y1, X2, Y2))
  ]
).
action(move_table_to_block_end(Agent, Block1, Block2, X1, Y1, X2, Y2),
  [moving_table_to_block(Agent, Block1, Block2, X1, Y1, X2, Y2), clear(Block2)],
  [],
  [],
  [agent(Agent)],
  [
    del(clear(Block2)), del(moving_table_to_block(Agent, Block1, Block2, X1, Y1, X2, Y2)),
    add(on(Block1, Block2)), add(available(Agent))
  ]
).
% Move a block from the top of another block to a position on the table
action(move_block_to_table_start(Agent, Block, X1, Y1, X2, Y2),
  [available(Agent), on(Block, Block2), at(Block, X1, Y1), at(Block2, X1, Y1), clear(Block)],
  [ontable(Block), on(_, Block), moving_block_to_table(_, Block, _, _, _, _), moving_block_to_block(_, Block, _, _, _, _, _)],
  [],
  [agent(Agent), pos(X1, Y1), pos(X2, Y2), block(Block), block(Block2), Block \= Block2],
  [
    del(available(Agent)), del(clear(Block)), del(on(Block, Block2)), del(at(Block, X1, Y1)),
    add(moving_block_to_table(Agent, Block, X1, Y1, X2, Y2))
  ]
).
action(move_block_to_table_end(Agent, Block, X1, Y1, X2, Y2),
  [moving_block_to_table(Agent, Block, X1, Y1, X2, Y2)],
  [at(X2, Y2)],
  [],
  [agent(Agent)],
  [
    del(moving_block_to_table(Agent, Block, X1, Y1, X2, Y2)),
    add(ontable(Block)), add(at(Block, X2, Y2)), add(clear(Block)), add(available(Agent))
  ]
).
% Move a block from the top of another block to the top of another block
action(move_block_to_block_start(Agent, Block1, Block2, X1, Y1, X2, Y2),
  [available(Agent), on(Block1, Block3), at(Block1, X1, Y1), at(Block2, X2, Y2), clear(Block2), clear(Block1)],
  [ontable(Block1), on(_, Block1)],
  [],
  [agent(Agent), pos(X1, Y1), pos(X2, Y2), block(Block1), block(Block2), block(Block3), Block1 \= Block2, Block1 \= Block3, Block2 \= Block3],
  [
    del(available(Agent)), del(clear(Block1)), del(on(Block1, Block3)), del(at(Block1, X1, Y1)),
    add(moving_block_to_block(Agent, Block1, Block2, X1, Y1, X2, Y2)), add(clear(Block3))
  ]
).
action(move_block_to_block_end(Agent, Block1, Block2, X1, Y1, X2, Y2),
  [moving_block_to_block(Agent, Block1, Block2, X1, Y1, X2, Y2), clear(Block2)],
  [],
  [],
  [agent(Agent)],
  [
    del(clear(Block2)), del(moving_block_to_block(Agent, Block1, Block2, X1, Y1, X2, Y2)),
    add(on(Block1, Block2)), add(at(Block1, X2, Y2)), add(clear(Block1)), add(available(Agent))
  ]
).


%%%%%%%%%%%%%%%%%%%%%%%
% ll_actions
%%%%%%%%%%%%%%%%%%%%%%%
ll_action(move_arm_start(Agent, X1, Y1, X2, Y2),
  [ll_arm_at(Agent, X1, Y1)],
  [moving_arm(Agent, _, _, _, _, _, _), gripping(Agent, _), releasing(Agent)],
  [],
  [ll_arm(Agent), pos(X1, Y1), pos(X2, Y2)],
  [
    add(moving_arm(Agent, X1, Y1, X2, Y2)),
    del(ll_arm_at(Agent, X1, Y1))
  ]
).

ll_action(move_arm_end(Agent, X1, Y1, X2, Y2),
  [moving_arm(Agent, X1, Y1, X2, Y2)],
  [],
  [],
  [ll_arm(Agent)],
  [
    del(moving_arm(Agent, X1, Y1, X2, Y2)),
    add(ll_arm_at(Agent, X2, Y2))
  ]
).

ll_action(close_gripper_start(Agent),
  [ll_gripper(Agent, open)],
  [moving_arm(Agent, _, _, _, _, _, _), gripping(Agent, _), releasing(Agent), gripped(Agent)],
  [],
  [ll_gripper(Agent)],
  [
    del(ll_gripper(Agent, open)),
    add(gripping(Agent, _))
  ]
).

ll_action(close_gripper_end(Agent),
  [gripping(Agent, _)],
  [],
  [],
  [ll_gripper(Agent)],
  [
    del(gripping(Agent, _)),
    add(gripped(Agent)), add(ll_gripper(Agent, close))
  ]
).

ll_action(open_gripper_start(Agent),
  [gripped(Agent)],
  [moving_arm(Agent, _, _, _, _, _, _), gripping(Agent, _), releasing(Agent)],
  [],
  [ll_gripper(Agent)],
  [
    del(gripped(Agent)), del(ll_gripper(Agent, close)),
    add(releasing(Agent))
  ]
).

ll_action(open_gripper_end(Agent),
  [releasing(Agent)],
  [],
  [],
  [ll_gripper(Agent)],
  [
    del(releasing(Agent)),
    add(ll_gripper(Agent, open))
  ]
).

%%%%%%%%%%%%%%%%%%%%%%%
% mappings
%%%%%%%%%%%%%%%%%%%%%%%
mapping(move_table_to_table_start(Agent, Block, X1, Y1, X2, Y2),
  [
    move_arm_start(Agent, X1, Y1, X2, Y2),
    move_arm_end(Agent, X1, Y1, X2, Y2)
  ]
).

mapping(move_table_to_block_start(Agent, Block1, Block2, X1, Y1, X2, Y2),
  [
    move_arm_start(Agent, X1, Y1, X2, Y2),
    move_arm_end(Agent, X1, Y1, X2, Y2),
    close_gripper_start(Agent),
    close_gripper_end(Agent)
  ]
).

mapping(move_block_to_table_start(Agent, Block, X1, Y1, X2, Y2),
  [
    move_arm_start(Agent, X1, Y1, X2, Y2),
    move_arm_end(Agent, X1, Y1, X2, Y2)
  ]
).

mapping(move_block_to_block_start(Agent, Block1, Block2, X1, Y1, X2, Y2),
  [
    move_arm_start(Agent, X1, Y1, X2, Y2),
    move_arm_end(Agent, X1, Y1, X2, Y2),
    open_gripper_start(Agent),
    open_gripper_end(Agent)
  ]
).
