% This file was automatically generated by the LLM system
%%%%%%%%%%%%%%%%%%%%%%%
% kb
%%%%%%%%%%%%%%%%%%%%%%%
% Define positions on the table
pos(1,1). pos(2,1). pos(3,1). pos(4,1). pos(5,1).
pos(6,1). pos(7,1). pos(8,1). pos(9,1). pos(10,1).
pos(11,1). pos(12,1). pos(13,1). pos(14,1). pos(15,1).
pos(16,1). pos(17,1). pos(18,1). pos(19,1). pos(20,1).
pos(4,4). pos(5,5).

% Define blocks
block(b1). block(b2). block(b3). block(b4). block(b5).
block(b6). block(b7). block(b8). block(b9). block(b10).
block(b11). block(b12). block(b13). block(b14). block(b15).
block(b16). block(b17). block(b18). block(b19). block(b20).

% Define agents
agent(a1). agent(a2). agent(a3).

% Define robotic arms as agents 
ll_arm(a1). ll_arm(a2). ll_arm(a3).

% Define resources
resources(agent(_)).
resources(ll_arm(_)).
resources(ll_gripper(_)).

%%%%%%%%%%%%%%%%%%%%%%%
% init
%%%%%%%%%%%%%%%%%%%%%%%
init_state([
  ontable(b1), ontable(b2), ontable(b3), ontable(b4), ontable(b5),
  ontable(b6), ontable(b7), ontable(b8), ontable(b9), ontable(b10),
  ontable(b11), ontable(b12), ontable(b13), ontable(b14), ontable(b15),
  ontable(b16), ontable(b17), ontable(b18), ontable(b19), ontable(b20),
  at(b1,1,1), at(b2,2,1), at(b3,3,1), at(b4,4,1), at(b5,5,1),
  at(b6,6,1), at(b7,7,1), at(b8,8,1), at(b9,9,1), at(b10,10,1),
  at(b11,11,1), at(b12,12,1), at(b13,13,1), at(b14,14,1), at(b15,15,1),
  at(b16,16,1), at(b17,17,1), at(b18,18,1), at(b19,19,1), at(b20,20,1),
  clear(b1), clear(b2), clear(b3), clear(b4), clear(b5),
  clear(b6), clear(b7), clear(b8), clear(b9), clear(b10),
  clear(b11), clear(b12), clear(b13), clear(b14), clear(b15),
  clear(b16), clear(b17), clear(b18), clear(b19), clear(b20),
  available(a1), available(a2), available(a3),
  ll_arm_at(a1, 2, 2), ll_arm_at(a2, 3, 3), ll_arm_at(a3, 5, 5),
  ll_gripper(a1, open), ll_gripper(a2, open), ll_gripper(a3, open)
]).

%%%%%%%%%%%%%%%%%%%%%%%
% goal
%%%%%%%%%%%%%%%%%%%%%%%
goal_state([
  ontable(b1), on(b2,b1), on(b3,b2),
  at(b1,4,4), at(b2,4,4), at(b3,4,4),
  clear(b3),
  available(a1), available(a2), available(a3),
  ll_arm_at(a1, _, _), ll_arm_at(a2, _, _), ll_arm_at(a3, _, _),
  ll_gripper(a1, _), ll_gripper(a2, _), ll_gripper(a3, _)
]).

%%%%%%%%%%%%%%%%%%%%%%%
% actions
%%%%%%%%%%%%%%%%%%%%%%%
% Move a block from a position on the table to another position on the table
action(move_block_table_to_table_start(Agent, Block, X1, Y1, X2, Y2),
  [available(Agent), ontable(Block), at(Block, X1, Y1), clear(Block)],
  [at(_, X2, Y2)],
  [],
  [agent(Agent), pos(X1, Y1), pos(X2, Y2), X1\=X2, Y1\=Y2, block(Block)],
  [
    del(available(Agent)), del(clear(Block)), del(ontable(Block)), del(at(Block, X1, Y1)),
    add(moving(Agent, Block, X1, Y1, X2, Y2))
  ]
).
action(move_block_table_to_table_end(Agent, Block, X1, Y1, X2, Y2),
  [moving(Agent, Block, X1, Y1, X2, Y2)],
  [at(_, X2, Y2)],
  [],
  [agent(Agent)],
  [
    del(moving(Agent, Block, X1, Y1, X2, Y2)),
    add(available(Agent)), add(clear(Block)), add(ontable(Block)), add(at(Block, X2, Y2))
  ]
).

% Move a block from the table to the top of another block
action(move_block_table_to_block_start(Agent, Block1, Block2, X1, Y1, X2, Y2),
  [available(Agent), ontable(Block1), at(Block1, X1, Y1), clear(Block1), at(Block2, X2, Y2), clear(Block2)],
  [],
  [],
  [agent(Agent), pos(X1, Y1), pos(X2, Y2), X1\=X2, Y1\=Y2, block(Block1), block(Block2)],
  [
    del(available(Agent)), del(clear(Block1)), del(ontable(Block1)), del(at(Block1, X1, Y1)),
    add(moving(Agent, Block1, X1, Y1, X2, Y2))
  ]
).
action(move_block_table_to_block_end(Agent, Block1, Block2, X1, Y1, X2, Y2),
  [moving(Agent, Block1, X1, Y1, X2, Y2)],
  [],
  [],
  [agent(Agent), block(Block1), block(Block2)],
  [
    del(moving(Agent, Block1, X1, Y1, X2, Y2)), del(clear(Block2)),
    add(available(Agent)), add(on(Block1, Block2)), add(at(Block1, X2, Y2)), add(clear(Block1))
  ]
).

% Move a block from the top of a block to another position on the table
action(move_block_block_to_table_start(Agent, Block1, Block2, X1, Y1, X2, Y2),
  [available(Agent), on(Block1, Block2), at(Block1, X1, Y1), clear(Block1)],
  [at(_, X2, Y2)],
  [],
  [agent(Agent), pos(X1, Y1), pos(X2, Y2), X1\=X2, Y1\=Y2, block(Block1), block(Block2)],
  [
    del(available(Agent)), del(clear(Block1)), del(on(Block1, Block2)),
    add(moving(Agent, Block1, X1, Y1, X2, Y2)), add(clear(Block2))
  ]
).
action(move_block_block_to_table_end(Agent, Block1, Block2, X1, Y1, X2, Y2),
  [moving(Agent, Block1, X1, Y1, X2, Y2)],
  [at(_, X2, Y2)],
  [],
  [agent(Agent), block(Block1)],
  [
    del(moving(Agent, Block1, X1, Y1, X2, Y2)),
    add(available(Agent)), add(clear(Block1)), add(ontable(Block1)), add(at(Block1, X2, Y2))
  ]
).

% Move a block from the top of a block to the top of another block
action(move_block_block_to_block_start(Agent, Block1, Block2, Block3, X1, Y1, X2, Y2),
  [available(Agent), on(Block1, Block2), at(Block1, X1, Y1), clear(Block1), at(Block3, X2, Y2), clear(Block3)],
  [],
  [],
  [agent(Agent), block(Block1), block(Block2), block(Block3), pos(X1, Y1), pos(X2, Y2), X1\=X2, Y1\=Y2,],
  [
    del(available(Agent)), del(clear(Block1)), del(on(Block1, Block2)),
    add(moving(Agent, Block1, X1, Y1, X2, Y2)), add(clear(Block2))
  ]
).
action(move_block_block_to_block_end(Agent, Block1, Block2, Block3, X1, Y1, X2, Y2),
  [moving(Agent, Block1, X1, Y1, X2, Y2)],
  [],
  [],
  [agent(Agent), block(Block1), block(Block3)],
  [
    del(moving(Agent, Block1, X1, Y1, X2, Y2)), del(clear(Block3)),
    add(available(Agent)), add(on(Block1, Block3)), add(at(Block1, X2, Y2))
  ]
).


%%%%%%%%%%%%%%%%%%%%%%%
% ll_actions
%%%%%%%%%%%%%%%%%%%%%%%
% Low-level action for starting to move the robotic arm
ll_action(move_arm_start(Arm, X1, Y1, X2, Y2),
  [ll_arm_at(Arm, X1, Y1)],
  [ll_arm_at(_, X2, Y2)],
  [],
  [ll_arm(Arm), ll_arm(Arm2)],
  [
    del(ll_arm_at(Arm, X1, Y1)),
    add(ll_moving_arm(Arm, X1, Y1, X2, Y2))
  ]
).

% Low-level action for completing the movement of the robotic arm
ll_action(move_arm_end(Arm, X1, Y1, X2, Y2),
  [ll_moving_arm(Arm, X1, Y1, X2, Y2)],
  [],
  [],
  [ll_arm(Arm)],
  [
    del(ll_moving_arm(Arm, X1, Y1, X2, Y2)),
    add(ll_arm_at(Arm, X2, Y2))
  ]
).

% Low-level action for starting to close the gripper
ll_action(close_start(Arm),
  [ll_gripper(Arm, open)],
  [ll_gripper(Arm, close)],
  [],
  [ll_arm(Arm)],
  [
    del(ll_gripper(Arm, open)),
    add(ll_closing_gripper(Arm))
  ]
).

% Low-level action for indicating the gripper has closed
ll_action(close_end(Arm),
  [ll_closing_gripper(Arm)],
  [],
  [],
  [ll_arm(Arm)],
  [
    del(ll_closing_gripper(Arm)),
    add(ll_gripper(Arm, close))
  ]
).

% Low-level action for starting to open the gripper
ll_action(open_start(Arm),
  [ll_gripper(Arm, close)],
  [ll_gripper(Arm, open)],
  [],
  [ll_arm(Arm)],
  [
    del(ll_gripper(Arm, close)),
    add(ll_opening_gripper(Arm))
  ]
).

% Low-level action for indicating the gripper has opened
ll_action(open_end(Arm),
  [ll_opening_gripper(Arm)],
  [],
  [],
  [ll_arm(Arm)],
  [
    del(ll_opening_gripper(Arm)),
    add(ll_gripper(Arm, open))
  ]
).

%%%%%%%%%%%%%%%%%%%%%%%
% mappings
%%%%%%%%%%%%%%%%%%%%%%%
% Mapping for moving a block from the table to another position on the table
mapping(move_block_table_to_table_start(Agent, Block, X1, Y1, X2, Y2),
  [
    move_arm_start(Agent, _, _, X1, Y1),
    move_arm_end(Agent, _, _, X1, Y1),
    close_start(Agent),
    close_end(Agent),
    move_arm_start(Agent, X1, Y1, X2, Y2),
    move_arm_end(Agent, X1, Y1, X2, Y2),
    open_start(Agent),
    open_end(Agent)
  ]
).

% Mapping for moving a block from the table to the top of another block
mapping(move_block_table_to_block_start(Agent, Block1, Block2, X1, Y1, X2, Y2),
  [
    move_arm_start(Agent, _, _, X1, Y1),
    move_arm_end(Agent, _, _, X1, Y1),
    close_start(Agent),
    close_end(Agent),
    move_arm_start(Agent, X1, Y1, X2, Y2),
    move_arm_end(Agent, X1, Y1, X2, Y2),
    open_start(Agent),
    open_end(Agent)
  ]
).

% Mapping for moving a block from the top of a block to another position on the table
mapping(move_block_block_to_table_start(Agent, Block1, Block2, X1, Y1, X2, Y2),
  [
    move_arm_start(Agent, _, _, X1, Y1),
    move_arm_end(Agent, _, _, X1, Y1),
    close_start(Agent),
    close_end(Agent),
    move_arm_start(Agent, X1, Y1, X2, Y2),
    move_arm_end(Agent, X1, Y1, X2, Y2),
    open_start(Agent),
    open_end(Agent)
  ]
).

% Mapping for moving a block from the top of a block to the top of another block
mapping(move_block_block_to_block_start(Agent, Block1, Block2, Block3, X1, Y1, X2, Y2),
  [
    move_arm_start(Agent, _, _, X1, Y1),
    move_arm_end(Agent, _, _, X1, Y1),
    close_start(Agent),
    close_end(Agent),
    move_arm_start(Agent, X1, Y1, X2, Y2),
    move_arm_end(Agent, X1, Y1, X2, Y2),
    open_start(Agent),
    open_end(Agent)
  ]
).