% This file was automatically generated by the LLM system
%%%%%%%%%%%%%%%%%%%%%%%
% kb
%%%%%%%%%%%%%%%%%%%%%%%
% Locations
location(location1).
location(location2).

% Containers
container(c1).
container(c2).

% Robot
robot(r1).

% Cranes
crane(crane1).
crane(crane2).

% Connections
connected(location1, location2).
connected(location2, location1).

% Low-level predicates for robot movement
ll_move_start(robot, locationFrom, locationTo).
ll_move_end(robot, locationFrom, locationTo).

% Low-level predicates for crane operations
ll_go_to_c_start(crane, container).
ll_go_to_c_end(crane, container).
ll_close_start(crane).
ll_close_end(crane).
ll_open_start(crane).
ll_open_end(crane).

% Resources
resources([robot(r1), crane(crane1), crane(crane2)]).
resources(ll_move_start(_, _, _)).
resources(ll_move_end(_, _, _)).
resources(ll_go_to_c_start(_, _)).
resources(ll_go_to_c_end(_, _)).
resources(ll_close_start(_)).
resources(ll_close_end(_)).
resources(ll_open_start(_)).
resources(ll_open_end(_)).

%%%%%%%%%%%%%%%%%%%%%%%
% init
%%%%%%%%%%%%%%%%%%%%%%%
init_state([
  at(c1, location1, ground), at(c2, location1, c1),
  at(r1, location1), 
  clear(c2), clear(r1), 
  available(crane1), available(crane2),
  ll_robot_at(r1, location1),
  ll_crane_at(crane1, location1), ll_crane_at(crane2, location1),
  ll_gripper(crane1, open), ll_gripper(crane2, open)
]).

%%%%%%%%%%%%%%%%%%%%%%%
% goal
%%%%%%%%%%%%%%%%%%%%%%%
goal_state([
  at(c1, location1, ground), at(c2, location2, ground),
  at(r1, location2), 
  clear(c1), clear(c2), clear(r1), 
  available(crane1), available(crane2),
  ll_robot_at(r1, location2),
  ll_crane_at(crane1, _), ll_crane_at(crane2, _),
  ll_gripper(crane1, _), ll_gripper(crane2, _)
]).

%%%%%%%%%%%%%%%%%%%%%%%
% actions
%%%%%%%%%%%%%%%%%%%%%%%
% Move a container from the ground to the top of another container within the same location
action(move_ground_to_top_start(Crane, Container1, Container2, Location),
  [available(Crane), at(Container1, Location, ground), at(Container2, Location, _), clear(Container1), clear(Container2)],
  [moving_ground_to_top(_, _, _, _), moving_top_to_ground(_, _, _, _), moving_top_to_top(_, _, _, _, _), moving_ground_to_robot(_, _, _, _), moving_robot_to_ground(_, _, _, _), moving_robot_to_top(_, _, _, _, _)],
  [],
  [crane(Crane), container(Container1), container(Container2), location(Location), Container1 \= Container2],
  [
    del(available(Crane)), del(clear(Container1)), del(at(Container1, Location, ground)),
    add(moving_ground_to_top(Crane, Container1, Container2, Location))
  ]
).
action(move_ground_to_top_end(Crane, Container1, Container2, Location),
  [moving_ground_to_top(Crane, Container1, Container2, Location)],
  [],
  [],
  [crane(Crane)],
  [
    del(moving_ground_to_top(Crane, Container1, Container2, Location)),
    add(on(Container1, Container2)), add(at(Container1, Location, Container2)), add(clear(Container1)), add(available(Crane))
  ]
).

% Move a container from the top of another container to the ground within the same location
action(move_top_to_ground_start(Crane, Container1, Container2, Location),
  [available(Crane), at(Container1, Location, Container2), clear(Container1)],
  [moving_ground_to_top(_, _, _, _), moving_top_to_ground(_, _, _, _), moving_top_to_top(_, _, _, _, _), moving_ground_to_robot(_, _, _, _), moving_robot_to_ground(_, _, _, _), moving_robot_to_top(_, _, _, _, _)],
  [],
  [crane(Crane), container(Container1), container(Container2), location(Location), Container1 \= Container2],
  [
    del(available(Crane)), del(clear(Container1)), del(at(Container1, Location, Container2)),
    add(moving_top_to_ground(Crane, Container1, Container2, Location)), add(clear(Container2))
  ]
).
action(move_top_to_ground_end(Crane, Container1, Container2, Location),
  [moving_top_to_ground(Crane, Container1, Container2, Location)],
  [],
  [],
  [crane(Crane)],
  [
    del(moving_top_to_ground(Crane, Container1, Container2, Location)),
    add(at(Container1, Location, ground)), add(clear(Container1)), add(available(Crane))
  ]
).

% Move a container from the top of another container to the top of a different container within the same location
action(move_top_to_top_start(Crane, Container1, Container2, Container3, Location),
  [available(Crane), at(Container1, Location, Container2), at(Container3, Location, _), clear(Container1), clear(Container3)],
  [moving_ground_to_top(_, _, _, _), moving_top_to_ground(_, _, _, _), moving_top_to_top(_, _, _, _, _), moving_ground_to_robot(_, _, _, _), moving_robot_to_ground(_, _, _, _), moving_robot_to_top(_, _, _, _, _)],
  [],
  [crane(Crane), container(Container1), container(Container2), container(Container3), location(Location), Container1 \= Container2, Container1 \= Container3, Container2 \= Container3],
  [
    del(available(Crane)), del(clear(Container1)), del(at(Container1, Location, Container2)),
    add(moving_top_to_top(Crane, Container1, Container2, Container3, Location)), add(clear(Container2))
  ]
).
action(move_top_to_top_end(Crane, Container1, Container2, Container3, Location),
  [moving_top_to_top(Crane, Container1, Container2, Container3, Location)],
  [],
  [],
  [crane(Crane)],
  [
    del(moving_top_to_top(Crane, Container1, Container2, Container3, Location)),
    add(on(Container1, Container3)), add(at(Container1, Location, Container3)), add(clear(Container1)), add(available(Crane))
  ]
).

% Load a container onto the robot
action(load_robot_start(Crane, Robot, Container, Location),
  [available(Crane), at(Container, Location, ground), at(Robot, Location), clear(Container), clear(Robot)],
  [moving_ground_to_top(_, _, _, _), moving_top_to_ground(_, _, _, _), moving_top_to_top(_, _, _, _, _), moving_ground_to_robot(_, _, _, _), moving_robot_to_ground(_, _, _, _), moving_robot_to_top(_, _, _, _, _)],
  [],
  [crane(Crane), robot(Robot), container(Container), location(Location)],
  [
    del(available(Crane)), del(clear(Container)), del(at(Container, Location, ground)),
    add(moving_ground_to_robot(Crane, Robot, Container, Location))
  ]
).
action(load_robot_end(Crane, Robot, Container, Location),
  [moving_ground_to_robot(Crane, Robot, Container, Location)],
  [],
  [],
  [crane(Crane)],
  [
    del(moving_ground_to_robot(Crane, Robot, Container, Location)),
    add(on(Container, Robot)), add(at(Container, Location, Robot)), add(clear(Container)), add(available(Crane))
  ]
).

% Unload a container from the robot to the ground
action(unload_robot_start(Crane, Robot, Container, Location),
  [available(Crane), at(Container, Location, Robot), at(Robot, Location), clear(Container)],
  [moving_ground_to_top(_, _, _, _), moving_top_to_ground(_, _, _, _), moving_top_to_top(_, _, _, _, _), moving_ground_to_robot(_, _, _, _), moving_robot_to_ground(_, _, _, _), moving_robot_to_top(_, _, _, _, _)],
  [],
  [crane(Crane), robot(Robot), container(Container), location(Location)],
  [
    del(available(Crane)), del(clear(Container)), del(at(Container, Location, Robot)),
    add(moving_robot_to_ground(Crane, Robot, Container, Location))
  ]
).
action(unload_robot_end(Crane, Robot, Container, Location),
  [moving_robot_to_ground(Crane, Robot, Container, Location)],
  [],
  [],
  [crane(Crane)],
  [
    del(moving_robot_to_ground(Crane, Robot, Container, Location)),
    add(at(Container, Location, ground)), add(clear(Container)), add(available(Crane))
  ]
).

% Move the robot from one location to another while carrying a container
action(move_robot_start(Robot, Container, Location1, Location2),
  [at(Robot, Location1), at(Container, Location1, Robot), clear(Robot)],
  [moving_ground_to_top(_, _, _, _), moving_top_to_ground(_, _, _, _), moving_top_to_top(_, _, _, _, _), moving_ground_to_robot(_, _, _, _), moving_robot_to_ground(_, _, _, _), moving_robot_to_top(_, _, _, _, _)],
  [],
  [robot(Robot), container(Container), location(Location1), location(Location2), connected(Location1, Location2)],
  [
    del(at(Robot, Location1)), del(at(Container, Location1, Robot)),
    add(moving_robot(Robot, Container, Location1, Location2))
  ]
).
action(move_robot_end(Robot, Container, Location1, Location2),
  [moving_robot(Robot, Container, Location1, Location2)],
  [],
  [],
  [robot(Robot)],
  [
    del(moving_robot(Robot, Container, Location1, Location2)),
    add(at(Robot, Location2)), add(at(Container, Location2, Robot)), add(clear(Robot))
  ]
).

%%%%%%%%%%%%%%%%%%%%%%%
% ll_actions
%%%%%%%%%%%%%%%%%%%%%%%
% Move the robot from one location to another
ll_action(ll_move_start(Robot, LocationFrom, LocationTo),
  [at(Robot, LocationFrom)],
  [moving_robot(Robot, _, _, _)],
  [],
  [robot(Robot), location(LocationFrom), location(LocationTo), connected(LocationFrom, LocationTo)],
  [
    del(at(Robot, LocationFrom)),
    add(moving_robot(Robot, LocationFrom, LocationTo))
  ]
).
ll_action(ll_move_end(Robot, LocationFrom, LocationTo),
  [moving_robot(Robot, LocationFrom, LocationTo)],
  [],
  [],
  [robot(Robot)],
  [
    del(moving_robot(Robot, LocationFrom, LocationTo)),
    add(at(Robot, LocationTo))
  ]
).

% Move the crane to the top of a container
ll_action(ll_go_to_c_start(Crane, Container),
  [available(Crane), at(Container, Location, _)],
  [moving_crane(Crane, _, _)],
  [],
  [crane(Crane), container(Container), location(Location)],
  [
    del(available(Crane)),
    add(moving_crane(Crane, Container, Location))
  ]
).
ll_action(ll_go_to_c_end(Crane, Container),
  [moving_crane(Crane, Container, Location)],
  [],
  [],
  [crane(Crane)],
  [
    del(moving_crane(Crane, Container, Location)),
    add(at(Crane, Location, Container)),
    add(available(Crane))
  ]
).

% Close the crane's gripper
ll_action(ll_close_start(Crane),
  [available(Crane)],
  [closing_gripper(Crane)],
  [],
  [crane(Crane)],
  [
    del(available(Crane)),
    add(closing_gripper(Crane))
  ]
).
ll_action(ll_close_end(Crane),
  [closing_gripper(Crane)],
  [],
  [],
  [crane(Crane)],
  [
    del(closing_gripper(Crane)),
    add(gripper_closed(Crane)),
    add(available(Crane))
  ]
).

% Open the crane's gripper
ll_action(ll_open_start(Crane),
  [available(Crane)],
  [opening_gripper(Crane)],
  [],
  [crane(Crane)],
  [
    del(available(Crane)),
    add(opening_gripper(Crane))
  ]
).
ll_action(ll_open_end(Crane),
  [opening_gripper(Crane)],
  [],
  [],
  [crane(Crane)],
  [
    del(opening_gripper(Crane)),
    add(gripper_open(Crane)),
    add(available(Crane))
  ]
).

%%%%%%%%%%%%%%%%%%%%%%%
% mappings
%%%%%%%%%%%%%%%%%%%%%%%
% Move a container from the ground to the top of another container within the same location
mapping(move_ground_to_top_start(Crane, Container1, Container2, Location),
  [
    ll_go_to_c_start(Crane, Container1),
    ll_go_to_c_end(Crane, Container1),
    ll_close_start(Crane),
    ll_close_end(Crane),
    ll_go_to_c_start(Crane, Container2),
    ll_go_to_c_end(Crane, Container2),
    ll_open_start(Crane),
    ll_open_end(Crane)
  ]
).

% Move a container from the top of another container to the ground within the same location
mapping(move_top_to_ground_start(Crane, Container1, Container2, Location),
  [
    ll_go_to_c_start(Crane, Container1),
    ll_go_to_c_end(Crane, Container1),
    ll_close_start(Crane),
    ll_close_end(Crane),
    ll_go_to_c_start(Crane, ground),
    ll_go_to_c_end(Crane, ground),
    ll_open_start(Crane),
    ll_open_end(Crane)
  ]
).

% Move a container from the top of another container to the top of a different container within the same location
mapping(move_top_to_top_start(Crane, Container1, Container2, Container3, Location),
  [
    ll_go_to_c_start(Crane, Container1),
    ll_go_to_c_end(Crane, Container1),
    ll_close_start(Crane),
    ll_close_end(Crane),
    ll_go_to_c_start(Crane, Container3),
    ll_go_to_c_end(Crane, Container3),
    ll_open_start(Crane),
    ll_open_end(Crane)
  ]
).

% Load a container onto the robot
mapping(load_robot_start(Crane, Robot, Container, Location),
  [
    ll_go_to_c_start(Crane, Container),
    ll_go_to_c_end(Crane, Container),
    ll_close_start(Crane),
    ll_close_end(Crane),
    ll_go_to_c_start(Crane, Robot),
    ll_go_to_c_end(Crane, Robot),
    ll_open_start(Crane),
    ll_open_end(Crane)
  ]
).

% Unload a container from the robot to the ground
mapping(unload_robot_start(Crane, Robot, Container, Location),
  [
    ll_go_to_c_start(Crane, Container),
    ll_go_to_c_end(Crane, Container),
    ll_close_start(Crane),
    ll_close_end(Crane),
    ll_go_to_c_start(Crane, ground),
    ll_go_to_c_end(Crane, ground),
    ll_open_start(Crane),
    ll_open_end(Crane)
  ]
).

% Move the robot from one location to another while carrying a container
mapping(move_robot_start(Robot, Container, Location1, Location2),
  [
    ll_move_start(Robot, Location1, Location2),
    ll_move_end(Robot, Location1, Location2)
  ]
).
